apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  #storageClassName: tkgs-storage-class-name
  resources:
    requests:
      storage: 2Gi
